version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: agenda_cupos_db
    environment:
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
      POSTGRES_DB: agenda_cupos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U agenda_user -d agenda_cupos']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
